analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - flutter-sdk/**
    - .dart_tool/**
    - test/**
    - "Veltrix Sports/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules: {}
