// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmseNI3VGRd1mIonnzO4P9tp8_xdDt8p4',
    appId: '1:25616595982:web:9858680bae4c42fcc8d05f',
    messagingSenderId: '25616595982',
    projectId: 'veltrix-sports',
    authDomain: 'veltrix-sports.firebaseapp.com',
    storageBucket: 'veltrix-sports.firebasestorage.app',
    measurementId: 'G-22EME77ENP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtl2l3e6m4eKxHP-_-wq2PcDPkom5z_o',
    appId: '1:25616595982:android:d3aa8cf032ea388fc8d05f',
    messagingSenderId: '25616595982',
    projectId: 'veltrix-sports',
    storageBucket: 'veltrix-sports.firebasestorage.app',
  );

  // iOS/macOS/Windows placeholders — run `flutterfire configure` to replace
  // with real app registrations. main.dart catches init failures so desktop
  // builds still launch without Firebase.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForIOS',
    appId: '1:25616595982:ios:placeholder',
    messagingSenderId: '25616595982',
    projectId: 'veltrix-sports',
    storageBucket: 'veltrix-sports.firebasestorage.app',
    iosClientId: '25616595982-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.veltrixsports.veltrixSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForMacOS',
    appId: '1:25616595982:macos:placeholder',
    messagingSenderId: '25616595982',
    projectId: 'veltrix-sports',
    storageBucket: 'veltrix-sports.firebasestorage.app',
    iosClientId: '25616595982-placeholder.apps.googleusercontent.com',
    iosBundleId: 'com.veltrixsports.veltrixSports',
  );

  // Firebase has no "Windows app" registration in the console: Flutter
  // desktop connects with the WEB app's credentials (same project, same
  // backend). The demo placeholders that used to be here made every Auth
  // and Firestore call fail on the Windows build.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmseNI3VGRd1mIonnzO4P9tp8_xdDt8p4',
    appId: '1:25616595982:web:9858680bae4c42fcc8d05f',
    messagingSenderId: '25616595982',
    projectId: 'veltrix-sports',
    authDomain: 'veltrix-sports.firebaseapp.com',
    storageBucket: 'veltrix-sports.firebasestorage.app',
    measurementId: 'G-22EME77ENP',
  );
}
